// e2e-program-journey.spec.js
// ---------------------------------------------------------------
// This is ONE continuous journey, not independent tests, because each stage
// depends on IDs generated by the stage before it (Program -> Promotion ->
// Release -> Lot -> Batch -> Campaign). To keep that shared state while still
// getting one row per stage in the dashboard report (instead of one giant
// test.step blob), we:
//   - use test.describe.configure({ mode: 'serial' }) so stages run in order
//     and a failure stops the remaining ones rather than cascading confusingly
//   - open ONE page in beforeAll and reuse it across every test() below,
//     instead of the default per-test page fixture
//   - keep a module-level `journey` object that each stage reads from and
//     writes into (program ID, release ID, lot ID, batch ID, campaign code...)
//
// Credentials come from .env (LOGIN_USERNAME / LOGIN_PASSWORD).
// Organization ID, promotion name, and program/release/lot/batch/campaign
// defaults come from test-data/test-config.json - change values there, not here.
// ---------------------------------------------------------------

const { test, expect } = require('@playwright/test');
const config = require('../test-data/test-config.json');
const { recordCode } = require('../utils/generatedCodesStore');

const { LoginPage } = require('../pages/LoginPage');
const { NavigationBar } = require('../pages/NavigationBar');
const { ProgramsPage } = require('../pages/ProgramsPage');
const { CreateProgramModal } = require('../pages/CreateProgramModal');
const { ProgramDetailPage } = require('../pages/ProgramDetailPage');
const { PromotionsPage } = require('../pages/PromotionsPage');
const { BatchPage } = require('../pages/BatchPage');
const { CampaignsPage } = require('../pages/CampaignsPage');

test.describe.configure({ mode: 'serial' });

/** @type {import('@playwright/test').Page} */
let page;

// Shared state carried between stages - this IS the point of this file.
const journey = {
  programName: null,
  programId: null,
  promotionId: null,
  promotionName: null,
  releaseId: null,
  releaseName: null,
  lotId: null,
  batchId: null,
  campaignId: null,
  viralCode: null,
};

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test.afterAll(async () => {
  await page.close();
});

test.describe('Login', () => {
  test('sign in via SSO/IAP', { tag: '@positive' }, async () => {
    const login = new LoginPage(page);

    await test.step('Open login page', async () => {
      await login.goto();
    });

    await test.step('Sign in with env credentials', async () => {
      await login.loginWithEnvCredentials();
    });

    await test.step('Confirm portal home loaded', async () => {
      await login.expectLoggedIn();
    });
  });
});

test.describe('Create Program', () => {
  test('create a new program from parameter file', { tag: '@positive' }, async () => {
    const nav = new NavigationBar(page);
    const programsPage = new ProgramsPage(page);
    const modal = new CreateProgramModal(page);

    await test.step('Open Programs page', async () => {
      await nav.goTo('Programs');
      await expect(programsPage.createNewBtn).toBeVisible();
    });

    await test.step('Open Create New Program modal', async () => {
      await programsPage.openCreateNewProgram();
      await expect(modal.dialog).toBeVisible();
    });

    await test.step('Fill program details from test-config.json', async () => {
      journey.programName = await modal.fillFromConfig(config.program);
    });

    await test.step('Save program', async () => {
      await modal.save();
    });

    await test.step('Capture generated Program ID', async () => {
      await programsPage.goto();
      journey.programId = await programsPage.getProgramIdByName(journey.programName);
      console.log(`[journey] Program created: ${journey.programName} (${journey.programId})`);
    });
  });
});

test.describe('Edit Program', () => {
  test('edit the created program', { tag: '@positive' }, async () => {
    const programsPage = new ProgramsPage(page);
    const detailPage = new ProgramDetailPage(page);

    await test.step('Open the created program', async () => {
      await programsPage.openProgramByName(journey.programName);
    });

    await test.step('Edit a field and save', async () => {
      await detailPage.openEdit();
      await detailPage.editProgramFields({ description: 'Updated by Playwright automation' });
    });
  });
});

test.describe('Create Promotion', () => {
  test('create a promotion mapped to the program', { tag: '@positive' }, async () => {
    const nav = new NavigationBar(page);
    const promotionsPage = new PromotionsPage(page);

    await test.step('Open Promotions page', async () => {
      await nav.goTo('Promotions');
      await promotionsPage.expectOnPage();
    });

    await test.step('Create promotion mapped to the program', async () => {
      const promoName = `${config.promotion.namePrefix}-${Date.now()}`;
      const result = await promotionsPage.createPromotionForProgram({
        programName: journey.programName,
        name: promoName,
        startDay: config.promotion.startDay,
        endDay: config.promotion.endDay,
      });
      journey.promotionId = result.promotionId;
      journey.promotionName = result.promotionName;
      console.log(`[journey] Promotion created: ${journey.promotionName} (${journey.promotionId})`);
    });
  });
});

test.describe('Create Release', () => {
  test('create a release for the program', { tag: '@positive' }, async () => {
    const programsPage = new ProgramsPage(page);
    const detailPage = new ProgramDetailPage(page);

    await test.step('Open the program', async () => {
      await programsPage.goto();
      await programsPage.openProgramByName(journey.programName);
    });

    await test.step('Create release', async () => {
      const releaseName = `${config.release.namePrefix}-${Date.now()}`;
      const result = await detailPage.createRelease({
        name: releaseName,
        startDay: config.release.startDay,
        endDay: config.release.endDay,
      });
      journey.releaseId = result.releaseId;
      journey.releaseName = result.releaseName;
      console.log(`[journey] Release created: ${journey.releaseName} (${journey.releaseId})`);
    });
  });
});

test.describe('Edit Release', () => {
  test('edit the created release', { tag: '@positive' }, async () => {
    const detailPage = new ProgramDetailPage(page);

    await test.step('Edit release end date', async () => {
      await detailPage.editRelease(journey.releaseId, { endDay: '30' }); // VERIFY: exact day
    });
  });
});

test.describe('Create Lot', () => {
  test('expand the release and create a lot', { tag: '@positive' }, async () => {
    const detailPage = new ProgramDetailPage(page);

    await test.step('Expand release row', async () => {
      await detailPage.expandRelease(journey.releaseId);
    });

    await test.step('Create lot', async () => {
      const lotName = `${config.lot.namePrefix}-${Date.now()}`;
      journey.lotId = await detailPage.addLot({ releaseId: journey.releaseId, name: lotName });
      console.log(`[journey] Lot created: ${lotName} (${journey.lotId})`);
    });
  });
});

test.describe('Edit Lot', () => {
  test('edit the created lot', { tag: '@positive' }, async () => {
    const detailPage = new ProgramDetailPage(page);

    await test.step('Edit lot name', async () => {
      await detailPage.editLot(journey.lotId, { name: `${config.lot.namePrefix}-updated` });
    });
  });
});

test.describe('Create Batch', () => {
  test('create a batch with organization and promotion from config', { tag: '@positive' }, async () => {
    const batchPage = new BatchPage(page);

    await test.step('Create batch', async () => {
      journey.batchId = await batchPage.createBatch({
        lotId: journey.lotId,
        organizationId: config.batch.organizationId, // parameter-driven, not hardcoded
        promotionName: journey.promotionName || config.batch.promotionName,
        codesPerFile: config.batch.codesPerFile,
      });
      console.log(`[journey] Batch created: ${journey.batchId}`);
    });

    await test.step('Trigger code generation', async () => {
      await batchPage.triggerCodeGeneration(journey.batchId);
    });

    await test.step('Wait for code generation to complete', async () => {
      await batchPage.waitForCodeGenComplete(journey.batchId);
    });
  });
});

test.describe('Campaigns', () => {
  test('create and edit a campaign, capture the generated code', { tag: '@positive' }, async () => {
    const programsPage = new ProgramsPage(page);
    const campaignsPage = new CampaignsPage(page);

    await test.step('Open the program and go to Campaigns tab', async () => {
      await programsPage.goto();
      await programsPage.openProgramByName(journey.programName);
      await campaignsPage.openTab();
    });

    await test.step('Create campaign', async () => {
      const campaignName = `${config.campaign.namePrefix}-${Date.now()}`;
      const result = await campaignsPage.createCampaign({ name: campaignName, day: 28 }); // VERIFY: exact day
      journey.campaignId = result.campaignId;
      journey.viralCode = result.viralCode;
    });

    await test.step('Edit campaign', async () => {
      await campaignsPage.editCampaign(journey.campaignId, { name: `${config.campaign.namePrefix}-updated` });
    });

    await test.step('Print and store the generated campaign code', async () => {
      recordCode({
        source: 'campaign',
        programId: journey.programId,
        campaignId: journey.campaignId,
        code: journey.viralCode,
      });

      // Also attach it directly to the HTML report for this test.
      await test.info().attach('generated-campaign-code', {
        body: journey.viralCode || 'NO CODE CAPTURED',
        contentType: 'text/plain',
      });
    });
  });
});
